###

POST https://lcaapi.herokuapp.com/Auths/authenticate
Content-Type: application/json

{
  "username": "tam@ekonect.no",
  "password": "ekonect2021"
}

###

GET https://lcaapi.herokuapp.com/api/Users/72337
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyMzM3Iiwicm9sZXMiOiJBZG1pbiIsIm5iZiI6MTYyNjk0MzY3NSwiZXhwIjoxNjI3NTQ4NDc1LCJpYXQiOjE2MjY5NDM2NzV9.uon8usotOnPDZuytLlz3kf7a2oozPBjo7cb6Ey2koTI 

{
}

###

GET https://localhost:44302/api/Users
Content-Type: application/json

{
}