import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Epd } from '../models/epd';

const unverifiedEpdsData = [
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
  {
    id: '37422',
    internal_number: 'MF6_test1_01032021',
    name: 'EPD with input from MF6',
    date: '12.01.2021',
    epd_unit: '1 Pcs',
    kg_per_du: '1000,0000',
    editor: 'Ole LCA.no',
    manufacturer: 'LCA.no AS',
    production_site: 'LCA.no AS',
    comments: 'Treteknisk får ikke opp unit når de legger inn råvarer. Dette må sjekkes.',
    pcr: 'NPCR 013:2019 Part B for Steel and aluminium construction products',
  },
] as Epd[];
@Injectable({
  providedIn: 'root',
})
export class EpdService {
  constructor() {}

  getUnverifiedEpds(): Observable<Epd[]> {
    return of(unverifiedEpdsData);
  }
}
